### LLM OpenAI data classification

This data notebook taps into the OpenAI API and does a simple analysis of a pandas dataframe. 

You will need the OpenAI Python library which you can install by typing `! pip install openai ` into an empty cell.

In [1]:
# ! pip install openai

In [2]:
from openai import OpenAI
import pandas as pd

#### Adding your API key
Then you need to open up an OpenA client using your API key. An API key is akin to a password. You can create an API key on OpenAI's [website](https://platform.openai.com/api-keys). Using OpenAI's API costs money and the company usually requires you to purchase credits to be able to use it. 

Once you have an API key and added credits, you can paste it into the string below next to `api_key=`. Note that `rate limits`, i.e. the number of times you can run your code and access the API may vary. You can read more about rate limits [here](https://platform.openai.com/docs/guides/rate-limits).

In [3]:
# Initialize the client with your API key
client = OpenAI(api_key="") # Replace with your actual API key

#### Calling the API 
The lines below help you call the API key.

In [4]:
# This creates a chat completion request
response = client.chat.completions.create(
     # this specifies which model you will use:
    model="gpt-3.5-turbo",
    messages=[
         # this gives instructions on how the model should behave:
        {"role": "system", "content": "You are a helpful assistant."},
         # this gives instructions on that the model should do:
        {"role": "user", "content": "Tell me a fun fact about space."}
    ]
)

Then you can print the model's response:

In [5]:
print(response.choices[0].message.content)

Sure! Did you know that there is a planet named HD 189733b that rains glass sideways in its atmosphere? The high-speed winds on this planet cause tiny particles of glass to be swept horizontally.

#### Analysis of speeches 

The data used in this exercise is a pared down version from this [data set of 900+ speeches made by U.S. Presidents](https://docs.google.com/spreadsheets/d/1YUuWcioqwX7kOx6CI278J2n25D2nVdLOHvkxlWNd9Ik/edit?gid=1455551723#gid=1455551723). It was downloaded from [Kaggle](http://kaggle.com/datasets/kboghe/presidentialspeeches?resource=download) and represents Presidential speeches given between 1789 and 2020. The data is a randomized sample of 5 speeches.

In [6]:
speeches = pd.read_csv("../data/presidential_speeches - radomized sample.csv")
speeches.head()

,President,Party,from,until,Vice President,title,date,info,speech
0,Gerald Ford,Republican,1974,1977,1.0,"April 23, 1975: Remarks at Tulane University",1975-04-23,"At Tulane University in New Orleans, President...","'Mr. President, President Hurley, Senator Joh..."
1,Lyndon B. Johnson,Democratic,1963,1969,1.0,"March 9, 1967: Press Conference",1967-03-09,President Johnson holds a press conference whe...,"'THE PRESIDENT. Good afternoon, ladies and ge..."
2,James Buchanan,Democratic,1857,1861,1.0,"June 22, 1860: Addendum to March 28 Message to...",1860-06-22,No info available,'In my message to the House of Representatives...
3,Richard M. Nixon,Republican,1969,1974,2.0,"September 23, 1952: ""Checkers"" Speech",1952-09-23,"'As a candidate for vice president, Richard Ni...",'My Fellow Americans:I come before you tonight...
4,Ronald Reagan,Republican,1981,1989,1.0,"November 4, 1983: Remarks on U.S. Casualties i...",1983-11-04,No info available,"'Officers and men and women of the corps, ladi..."

Make a function that responds to the content of each speech:

In [7]:
def getresponse(x):
    response = client.chat.completions.create(
         # this specifies which model you will use:
        model="gpt-3.5-turbo",
        messages=[
             # this gives instructions on how the model should behave:
            {"role": "system", "content": "You are helping me identify a presidential speech."},
             # this gives instructions on that the model should do:
            {"role": "user", "content": f"Here is a document: {x}\n\nTell me what year this speech is from and return only the full year."}
            ]
    )
    return response.choices[0].message.content

Create a new column and return the instructions set in the function in that column:

In [8]:
speeches["approximate_year"] = speeches["speech"].apply(getresponse)

In [9]:
speeches.head()

,President,Party,from,until,Vice President,title,date,info,speech,approximate_year
0,Gerald Ford,Republican,1974,1977,1.0,"April 23, 1975: Remarks at Tulane University",1975-04-23,"At Tulane University in New Orleans, President...","'Mr. President, President Hurley, Senator Joh...",This speech is from the year 1976.
1,Lyndon B. Johnson,Democratic,1963,1969,1.0,"March 9, 1967: Press Conference",1967-03-09,President Johnson holds a press conference whe...,"'THE PRESIDENT. Good afternoon, ladies and ge...",This speech is from the year 1967.
2,James Buchanan,Democratic,1857,1861,1.0,"June 22, 1860: Addendum to March 28 Message to...",1860-06-22,No info available,'In my message to the House of Representatives...,This speech is from the year 1868.
3,Richard M. Nixon,Republican,1969,1974,2.0,"September 23, 1952: ""Checkers"" Speech",1952-09-23,"'As a candidate for vice president, Richard Ni...",'My Fellow Americans:I come before you tonight...,This speech is from the year 1952.
4,Ronald Reagan,Republican,1981,1989,1.0,"November 4, 1983: Remarks on U.S. Casualties i...",1983-11-04,No info available,"'Officers and men and women of the corps, ladi...",This speech is from the year 1983.

In [10]:
speeches.to_csv("../output/classified_speeches.csv")