### Introduction to pandas!

What we will learn in this notebook:
- how to open and read in a csv spreadsheet
- how to look at the data we have
- how to select columns
- how to do some math with them

First we need to import pandas as a library. We import the library and then tell Python to refer to it as `pd`:

In [1]:
import pandas as pd

### Reading spreadsheets

This is how you read a spreadsheet and assign it to a variable:

In [2]:
census_data = pd.read_csv('../data/2016_census_data.csv')

### Looking at your data

To look at the data you just read into Python, you can just run a cell with the name of the variable:

In [3]:
census_data

,geoid,name,total_population,median_income,median_home_value,educational_attainment,white_alone,black_alone,native,asian,native_hawaiian_pacific_islander,some_other_race_alone,two_or_more,hispanic_or_latino
0,34003001000,"Census Tract 10, Bergen County, New Jersey",6767,151641.0,680000.0,3045.0,5667.0,75.0,0.0,759.0,0.0,0.0,132.0,134.0
1,34003002100,"Census Tract 21, Bergen County, New Jersey",1522,114545.0,2000001.0,836.0,788.0,141.0,0.0,444.0,0.0,0.0,27.0,122.0
2,34003002200,"Census Tract 22, Bergen County, New Jersey",5389,90647.0,453800.0,1791.0,3481.0,99.0,9.0,1247.0,0.0,36.0,19.0,504.0
3,34003002300,"Census Tract 23, Bergen County, New Jersey",5828,112031.0,610000.0,2363.0,3595.0,89.0,37.0,1627.0,0.0,0.0,32.0,448.0
4,34003003100,"Census Tract 31, Bergen County, New Jersey",4946,76906.0,301900.0,1588.0,1803.0,306.0,0.0,1435.0,0.0,13.0,24.0,1365.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4695,42103950701,"Census Tract 9507.01, Pike County, Pennsylvania",4107,61726.0,155800.0,537.0,3665.0,12.0,0.0,67.0,0.0,0.0,26.0,337.0
4696,42103950702,"Census Tract 9507.02, Pike County, Pennsylvania",3119,59239.0,151100.0,405.0,2908.0,44.0,0.0,60.0,0.0,0.0,19.0,88.0
4697,42103950801,"Census Tract 9508.01, Pike County, Pennsylvania",4403,55530.0,120000.0,718.0,2777.0,705.0,0.0,53.0,0.0,0.0,97.0,771.0
4698,42103950802,"Census Tract 9508.02, Pike County, Pennsylvania",6004,50724.0,146700.0,795.0,3072.0,970.0,20.0,44.0,0.0,0.0,11.0,1887.0
4699,42103950900,"Census Tract 9509, Pike County, Pennsylvania",4184,49453.0,146100.0,721.0,3888.0,55.0,29.0,22.0,0.0,0.0,9.0,181.0

Oops, that's a little long. Maybe we just want to see the first 10 rows:

In [4]:
census_data.head(10)

,geoid,name,total_population,median_income,median_home_value,educational_attainment,white_alone,black_alone,native,asian,native_hawaiian_pacific_islander,some_other_race_alone,two_or_more,hispanic_or_latino
0,34003001000,"Census Tract 10, Bergen County, New Jersey",6767,151641.0,680000.0,3045.0,5667.0,75.0,0.0,759.0,0.0,0.0,132.0,134.0
1,34003002100,"Census Tract 21, Bergen County, New Jersey",1522,114545.0,2000001.0,836.0,788.0,141.0,0.0,444.0,0.0,0.0,27.0,122.0
2,34003002200,"Census Tract 22, Bergen County, New Jersey",5389,90647.0,453800.0,1791.0,3481.0,99.0,9.0,1247.0,0.0,36.0,19.0,504.0
3,34003002300,"Census Tract 23, Bergen County, New Jersey",5828,112031.0,610000.0,2363.0,3595.0,89.0,37.0,1627.0,0.0,0.0,32.0,448.0
4,34003003100,"Census Tract 31, Bergen County, New Jersey",4946,76906.0,301900.0,1588.0,1803.0,306.0,0.0,1435.0,0.0,13.0,24.0,1365.0
5,34003003200,"Census Tract 32, Bergen County, New Jersey",5044,69531.0,322400.0,1417.0,1342.0,186.0,19.0,1882.0,0.0,6.0,64.0,1564.0
6,34003003300,"Census Tract 33, Bergen County, New Jersey",6638,97957.0,328100.0,1737.0,2437.0,400.0,0.0,2131.0,0.0,0.0,148.0,1522.0
7,34003003401,"Census Tract 34.01, Bergen County, New Jersey",2958,122650.0,385200.0,941.0,1704.0,109.0,0.0,520.0,0.0,0.0,36.0,589.0
8,34003003402,"Census Tract 34.02, Bergen County, New Jersey",3827,105776.0,356100.0,1237.0,1937.0,260.0,0.0,733.0,0.0,4.0,122.0,771.0
9,34003003500,"Census Tract 35, Bergen County, New Jersey",4100,52382.0,340200.0,891.0,886.0,502.0,16.0,1160.0,0.0,0.0,59.0,1493.0

Or the last four:

In [5]:
census_data.tail(4)

,geoid,name,total_population,median_income,median_home_value,educational_attainment,white_alone,black_alone,native,asian,native_hawaiian_pacific_islander,some_other_race_alone,two_or_more,hispanic_or_latino
4696,42103950702,"Census Tract 9507.02, Pike County, Pennsylvania",3119,59239.0,151100.0,405.0,2908.0,44.0,0.0,60.0,0.0,0.0,19.0,88.0
4697,42103950801,"Census Tract 9508.01, Pike County, Pennsylvania",4403,55530.0,120000.0,718.0,2777.0,705.0,0.0,53.0,0.0,0.0,97.0,771.0
4698,42103950802,"Census Tract 9508.02, Pike County, Pennsylvania",6004,50724.0,146700.0,795.0,3072.0,970.0,20.0,44.0,0.0,0.0,11.0,1887.0
4699,42103950900,"Census Tract 9509, Pike County, Pennsylvania",4184,49453.0,146100.0,721.0,3888.0,55.0,29.0,22.0,0.0,0.0,9.0,181.0

In [6]:
census_data.sample(5)

,geoid,name,total_population,median_income,median_home_value,educational_attainment,white_alone,black_alone,native,asian,native_hawaiian_pacific_islander,some_other_race_alone,two_or_more,hispanic_or_latino
4245,36103135201,"Census Tract 1352.01, Suffolk County, New York",2154,131554.0,429900.0,771.0,2007.0,1.0,0.0,125.0,0.0,0.0,14.0,7.0
3020,36061011401,"Census Tract 114.01, New York County, New York",1195,180607.0,2000001.0,807.0,1084.0,9.0,0.0,67.0,0.0,0.0,11.0,24.0
4481,36119001302,"Census Tract 13.02, Westchester County, New York",4026,31429.0,313900.0,580.0,868.0,700.0,0.0,299.0,0.0,0.0,0.0,2159.0
2444,36047076600,"Census Tract 766, Kings County, New York",2393,59653.0,810500.0,442.0,175.0,1925.0,0.0,12.0,0.0,11.0,41.0,229.0
4267,36103145807,"Census Tract 1458.07, Suffolk County, New York",4438,96734.0,337300.0,922.0,3594.0,165.0,0.0,147.0,0.0,25.0,25.0,482.0

or we want to know the length of the entire set:

In [7]:
len(census_data)

4700

In [8]:
census_data.T

,0,1,2,3,4,5,6,7,8,9,...,4690,4691,4692,4693,4694,4695,4696,4697,4698,4699
geoid,34003001000,34003002100,34003002200,34003002300,34003003100,34003003200,34003003300,34003003401,34003003402,34003003500,...,42103950502,42103950601,42103950603,42103950605,42103950606,42103950701,42103950702,42103950801,42103950802,42103950900
name,"Census Tract 10, Bergen County, New Jersey","Census Tract 21, Bergen County, New Jersey","Census Tract 22, Bergen County, New Jersey","Census Tract 23, Bergen County, New Jersey","Census Tract 31, Bergen County, New Jersey","Census Tract 32, Bergen County, New Jersey","Census Tract 33, Bergen County, New Jersey","Census Tract 34.01, Bergen County, New Jersey","Census Tract 34.02, Bergen County, New Jersey","Census Tract 35, Bergen County, New Jersey",...,"Census Tract 9505.02, Pike County, Pennsylvania","Census Tract 9506.01, Pike County, Pennsylvania","Census Tract 9506.03, Pike County, Pennsylvania","Census Tract 9506.05, Pike County, Pennsylvania","Census Tract 9506.06, Pike County, Pennsylvania","Census Tract 9507.01, Pike County, Pennsylvania","Census Tract 9507.02, Pike County, Pennsylvania","Census Tract 9508.01, Pike County, Pennsylvania","Census Tract 9508.02, Pike County, Pennsylvania","Census Tract 9509, Pike County, Pennsylvania"
total_population,6767,1522,5389,5828,4946,5044,6638,2958,3827,4100,...,3132,1560,1093,6056,5647,4107,3119,4403,6004,4184
median_income,151641.0,114545.0,90647.0,112031.0,76906.0,69531.0,97957.0,122650.0,105776.0,52382.0,...,57875.0,68319.0,56250.0,83220.0,86250.0,61726.0,59239.0,55530.0,50724.0,49453.0
median_home_value,680000.0,2000001.0,453800.0,610000.0,301900.0,322400.0,328100.0,385200.0,356100.0,340200.0,...,205300.0,269200.0,281400.0,207100.0,237300.0,155800.0,151100.0,120000.0,146700.0,146100.0
educational_attainment,3045.0,836.0,1791.0,2363.0,1588.0,1417.0,1737.0,941.0,1237.0,891.0,...,728.0,354.0,255.0,1048.0,1369.0,537.0,405.0,718.0,795.0,721.0
white_alone,5667.0,788.0,3481.0,3595.0,1803.0,1342.0,2437.0,1704.0,1937.0,886.0,...,2186.0,1404.0,1009.0,5487.0,4951.0,3665.0,2908.0,2777.0,3072.0,3888.0
black_alone,75.0,141.0,99.0,89.0,306.0,186.0,400.0,109.0,260.0,502.0,...,237.0,33.0,16.0,333.0,71.0,12.0,44.0,705.0,970.0,55.0
native,0.0,0.0,9.0,37.0,0.0,19.0,0.0,0.0,0.0,16.0,...,0.0,0.0,0.0,21.0,0.0,0.0,0.0,0.0,20.0,29.0
asian,759.0,444.0,1247.0,1627.0,1435.0,1882.0,2131.0,520.0,733.0,1160.0,...,120.0,11.0,0.0,0.0,156.0,67.0,60.0,53.0,44.0,22.0
native_hawaiian_pacific_islander,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,9.0,0.0,0.0,0.0,0.0,0.0,0.0
some_other_race_alone,0.0,0.0,36.0,0.0,13.0,6.0,0.0,0.0,4.0,0.0,...,31.0,0.0,0.0,11.0,12.0,0.0,0.0,0.0,0.0,0.0
two_or_more,132.0,27.0,19.0,32.0,24.0,64.0,148.0,36.0,122.0,59.0,...,75.0,53.0,16.0,0.0,20.0,26.0,19.0,97.0,11.0,9.0
hispanic_or_latino,134.0,122.0,504.0,448.0,1365.0,1564.0,1522.0,589.0,771.0,1493.0,...,483.0,59.0,52.0,195.0,437.0,337.0,88.0,771.0,1887.0,181.0

In [9]:
census_data.shape

(4700, 14)

In [10]:
census_data.info()

<class 'pandas.DataFrame'>
RangeIndex: 4700 entries, 0 to 4699
Data columns (total 14 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   geoid                             4700 non-null   int64
 1   name                              4700 non-null   str
 2   total_population                  4700 non-null   int64
 3   median_income                     4700 non-null   float64
 4   median_home_value                 4700 non-null   float64
 5   educational_attainment            4700 non-null   float64
 6   white_alone                       4700 non-null   float64
 7   black_alone                       4700 non-null   float64
 8   native                            4700 non-null   float64
 9   asian                             4700 non-null   float64
 10  native_hawaiian_pacific_islander  4700 non-null   float64
 11  some_other_race_alone             4700 non-null   float64
 12  two_or_more                       4700 non-null   float64
 13  hispanic_or_latino                4700 non-null   float64
dtypes: float64(11), int64(2), str(1)
memory usage: 514.2 KB

### Playing with columns

How about selecting columns? This is how you can do that:

In [11]:
census_data['black_alone']

0        75.0
1       141.0
2        99.0
3        89.0
4       306.0
        ...
4695     12.0
4696     44.0
4697    705.0
4698    970.0
4699     55.0
Name: black_alone, Length: 4700, dtype: float64

You can also select multiple columns:

In [12]:
column_names  = ['black_alone', 'native']
census_data[column_names]

      black_alone  native
0            75.0     0.0
1           141.0     0.0
2            99.0     9.0
3            89.0    37.0
4           306.0     0.0
...           ...     ...
4695         12.0     0.0
4696         44.0     0.0
4697        705.0     0.0
4698        970.0    20.0
4699         55.0    29.0

[4700 rows x 2 columns]

### Doing math with your data
There are a few nifty functions you can apply to your data columns.

In [13]:
census_data['black_alone'].sum()

np.float64(3155672.0)

In [14]:
census_data['black_alone'].median()

np.float64(198.5)

In [15]:
census_data['black_alone'].mean()

np.float64(671.4195744680851)

There is also this nifty function which gives you a quick overview of your data:

In [16]:
census_data['black_alone'].describe()

count     4700.000000
mean       671.419574
std       1041.216791
min          0.000000
25%         47.000000
50%        198.500000
75%        889.500000
max      17123.000000
Name: black_alone, dtype: float64

### Making new data columns
You can make a new column based on two columns like so:

In [17]:
census_data['black_alone_percentage'] = census_data['black_alone']/census_data['total_population']

In [18]:
census_data.head()

,geoid,name,total_population,median_income,median_home_value,educational_attainment,white_alone,black_alone,native,asian,native_hawaiian_pacific_islander,some_other_race_alone,two_or_more,hispanic_or_latino,black_alone_percentage
0,34003001000,"Census Tract 10, Bergen County, New Jersey",6767,151641.0,680000.0,3045.0,5667.0,75.0,0.0,759.0,0.0,0.0,132.0,134.0,0.011083
1,34003002100,"Census Tract 21, Bergen County, New Jersey",1522,114545.0,2000001.0,836.0,788.0,141.0,0.0,444.0,0.0,0.0,27.0,122.0,0.092641
2,34003002200,"Census Tract 22, Bergen County, New Jersey",5389,90647.0,453800.0,1791.0,3481.0,99.0,9.0,1247.0,0.0,36.0,19.0,504.0,0.018371
3,34003002300,"Census Tract 23, Bergen County, New Jersey",5828,112031.0,610000.0,2363.0,3595.0,89.0,37.0,1627.0,0.0,0.0,32.0,448.0,0.015271
4,34003003100,"Census Tract 31, Bergen County, New Jersey",4946,76906.0,301900.0,1588.0,1803.0,306.0,0.0,1435.0,0.0,13.0,24.0,1365.0,0.061868

To overwrite your previous data you can just re-assign the column new values, the way you do with any variable:

In [19]:
census_data['black_alone_percentage'] = (census_data['black_alone']/census_data['total_population'])*100

In [20]:
census_data.head()

,geoid,name,total_population,median_income,median_home_value,educational_attainment,white_alone,black_alone,native,asian,native_hawaiian_pacific_islander,some_other_race_alone,two_or_more,hispanic_or_latino,black_alone_percentage
0,34003001000,"Census Tract 10, Bergen County, New Jersey",6767,151641.0,680000.0,3045.0,5667.0,75.0,0.0,759.0,0.0,0.0,132.0,134.0,1.108320
1,34003002100,"Census Tract 21, Bergen County, New Jersey",1522,114545.0,2000001.0,836.0,788.0,141.0,0.0,444.0,0.0,0.0,27.0,122.0,9.264126
2,34003002200,"Census Tract 22, Bergen County, New Jersey",5389,90647.0,453800.0,1791.0,3481.0,99.0,9.0,1247.0,0.0,36.0,19.0,504.0,1.837076
3,34003002300,"Census Tract 23, Bergen County, New Jersey",5828,112031.0,610000.0,2363.0,3595.0,89.0,37.0,1627.0,0.0,0.0,32.0,448.0,1.527111
4,34003003100,"Census Tract 31, Bergen County, New Jersey",4946,76906.0,301900.0,1588.0,1803.0,306.0,0.0,1435.0,0.0,13.0,24.0,1365.0,6.186818

A quick sorting function can now help you find the spots with the highest or lowest black populations (we can go over this again next week):

In [21]:
census_data.sort_values(by='median_income', ascending = True)

,geoid,name,total_population,median_income,median_home_value,educational_attainment,white_alone,black_alone,native,asian,native_hawaiian_pacific_islander,some_other_race_alone,two_or_more,hispanic_or_latino,black_alone_percentage
3712,36081062400,"Census Tract 624, Queens County, New York",0,-666666666.0,-666666666.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN
3952,36081156700,"Census Tract 1567, Queens County, New York",1382,-666666666.0,663500.0,218.0,324.0,255.0,0.0,500.0,0.0,0.0,10.0,293.0,18.451520
1546,36005017100,"Census Tract 171, Bronx County, New York",0,-666666666.0,-666666666.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN
2533,36047096000,"Census Tract 960, Kings County, New York",0,-666666666.0,-666666666.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN
3928,36081138502,"Census Tract 1385.02, Queens County, New York",37,-666666666.0,-666666666.0,17.0,16.0,4.0,0.0,0.0,0.0,0.0,0.0,17.0,10.810811
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4532,36119004700,"Census Tract 47, Westchester County, New York",3596,250001.0,2000001.0,1649.0,3234.0,51.0,0.0,132.0,0.0,0.0,52.0,127.0,1.418242
141,34003047300,"Census Tract 473, Bergen County, New Jersey",3138,250001.0,1033800.0,1472.0,2603.0,41.0,0.0,324.0,0.0,0.0,79.0,91.0,1.306565
2925,36061002100,"Census Tract 21, New York County, New York",6488,250001.0,2000001.0,4168.0,4811.0,96.0,0.0,998.0,0.0,0.0,281.0,302.0,1.479655
359,34013020100,"Census Tract 201, Essex County, New Jersey",4593,250001.0,1418300.0,2713.0,3653.0,16.0,0.0,721.0,0.0,0.0,100.0,103.0,0.348356
4594,36119009800,"Census Tract 98, Westchester County, New York",4535,250001.0,1309100.0,2558.0,3514.0,29.0,0.0,593.0,8.0,0.0,124.0,267.0,0.639471