## This notebook runs through a few simple python things
- Data structures (in-depth)
    -  lists
    -  dictionaries
    -  lists of dictionaries
- Loops and conditionals, used with dictionaries

# Data structures in more depth

You may encounter data in various formats in your research or create data in various formats.

#### Lists
Lists are denoted by an opening and closing bracket and can contain multiple values, for example `["R2D2", "Yoda", "Han Solo"]`

In [1]:
names = ["R2D2", "Yoda", "Han Solo"]

#### Dictionary

A Python Dictionary is another common and powerful datatype.

Think of it as a collection of data points about a single element.

For example, a spaceship:
- show: Futurama
- type: spaceship
- name: Planet Express Ship
- cost: 40000
- on_sale: True

A dictionary would hold this data as **key: value** pairs and is usually wrapped in ```{}```.

Each key: value pair is separated by a comma.
The format is 
```
{
"key1_string": "string_value",
"key2_number": 12,
"key3_bolean": True
}
```

In [2]:
ufo1 = {
    "show": "Futurama",
    "type": "spaceship",
    "name": "Planet Express Ship",
    "cost": 40000,
    "on_sale": True
}

In [3]:
## call ufo1
ufo1

{'show': 'Futurama',
 'type': 'spaceship',
 'name': 'Planet Express Ship',
 'cost': 40000,
 'on_sale': True}

In [4]:
## what ufo1's datatype
type(ufo1)

dict

Let's build a dictionary called car_2 with the following data points.

Note: In this case the type is first. The order in a dictionary doesn't matter.

- type: spaceship
- show: Star Trek
- name: USS Enterprise
- cost: 35_000
- on_sale: True

In [5]:
## build ufo_2
ufo2 = {
    "type": "spaceship",
    "show": "Star Trek",
    "name": "USS Enterprise",
    "cost": 35_000,
    "on_sale": True
}

#### List of dictionaries 

We can now create a list with these two dictionaries

In [6]:
ufos = [ufo1, ufo2]

In [7]:
ufos

[{'show': 'Futurama',
  'type': 'spaceship',
  'name': 'Planet Express Ship',
  'cost': 40000,
  'on_sale': True},
 {'type': 'spaceship',
  'show': 'Star Trek',
  'name': 'USS Enterprise',
  'cost': 35000,
  'on_sale': True}]

## Loops
`For loops` are a way for programmers to iterate through a list of items and apply the same process to each item:

In [8]:
for x in names:
    # Instructions go here
    print("Instructions go here!")

Instructions go here!
Instructions go here!
Instructions go here!

In [9]:
for name in names:
    print(name)

R2D2
Yoda
Han Solo

Looping through a list of dictionaries:

In [10]:
for ufo in ufos:
    print(ufo)

{'show': 'Futurama', 'type': 'spaceship', 'name': 'Planet Express Ship', 'cost': 40000, 'on_sale': True}
{'type': 'spaceship', 'show': 'Star Trek', 'name': 'USS Enterprise', 'cost': 35000, 'on_sale': True}

In [11]:
for ufo in ufos:
    print(ufo["show"])

Futurama
Star Trek

Fun fact! `Lists` and `dictionaries` work well with pandas!

In [12]:
import pandas as pd

In [13]:
df = pd.DataFrame(ufos)
df.head()

        show       type                 name   cost  on_sale
0   Futurama  spaceship  Planet Express Ship  40000     True
1  Star Trek  spaceship       USS Enterprise  35000     True

In [14]:
df2 = pd.DataFrame(names)
df2.head()

          0
0      R2D2
1      Yoda
2  Han Solo

## Conditionals

Sometimes you will encounter tricky situations in your data gathering and analysis endeavors and it helps to know that you can instruct your python script to take different paths depending on what condition may be met. Meet the `if` clause:

In [15]:
alien = "jabba the hutt"

In [16]:
if alien == "yoda" :
    print("May the force be with you!")
else:
    print("It's a trap")

It's a trap

There are a number of operators you can use with conditionals

| Operators | What It Does                                                                                                          | Example                        |
|-----------|-----------------------------------------------------------------------------------------------------------------------|--------------------------------|
| ==        | If the values to the left and right of the operator are equal, then the condition is true.                            | ("pie" == "cake") is not true. |
| !=        | If the values to the left and right of the operator are not equal, then condition is true.                            | ("pie" != "cake") is true.     |
| >         | If the value of left operator is bigger than the value to the right, then condition is true.                          | (4 > 10) is not true.          |
| <         | If the value of left operator is smaller than the value to the right, then condition is true.                         | (4 < 10) is true.              |
| >=        | If the values to the left of the operator is greater than or equal to the value to the right, then condition is true. | (4 >= 10) is not true.         |
| <=        | If the values to the left of the operator is less than or equal to the value to the right, then condition is true.    | (4 <= 10) is true.             |

## Combining loops and if clauses
You can loop through lists and use if/else

In [17]:
for ufo in ufos:
    ufo_status = "too expensive" if ufo["cost"] > 36000 else "within my budget"
    print(f"The {ufo['name']} is {ufo_status}.")

The Planet Express Ship is too expensive.
The USS Enterprise is within my budget.